core/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    # Index
    url(r'^$', index, name='index'),
]

meal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Autocomplete
    url(r'^item-meal-autocomplete/$',
        views.ItemMealAutocomplete.as_view(), name='item_meal_autocomplete'),
    url(r'^plate-autocomplete/$',
        views.PlateAutocomplete.as_view(), name='plate_autocomplete'),
    url(r'^allergy-autocomplete/$',
        views.AllergyAutocomplete.as_view(), name='allergy_autocomplete'),
    # Meal
    url(r'^meal/list/$', views.MealList.as_view(), name='meal_list'),
    url(r'^meal/student/list/$',
        views.MealStudentList.as_view(), name='meal_student_list'),
    url(r'^meal/add/$', views.MealCreate.as_view(), name='meal_add'),
    url(r'^meal/details/(?P<pk>[0-9]+)/$',
        views.MealDetail.as_view(), name='meal_details'),
    url(r'^meal/edit/(?P<pk>[0-9]+)/$',
        views.MealUpdate.as_view(), name='meal_edit'),
    url(r'^meal/(?P<pk>[0-9]+)/delete/$',
        views.MealDelete.as_view(), name='meal_delete'),
    # ItemMeal
    url(r'^itemmeal/list/$',
        views.ItemMealList.as_view(), name='item_meal_list'),
    url(r'^itemmeal/add/$',
        views.ItemMealCreate.as_view(), name='item_meal_add'),
    url(r'^itemmeal/details/(?P<pk>[0-9]+)/$',
        views.ItemMealDetail.as_view(), name='item_meal_details'),
    url(r'^itemmeal/edit/(?P<pk>[0-9]+)/$',
        views.ItemMealUpdate.as_view(), name='item_meal_edit'),
    url(r'^itemmeal/(?P<pk>[0-9]+)/delete/$',
        views.ItemMealDelete.as_view(), name='item_meal_delete'),
    # Plate
    url(r'^plate/list/$', views.PlateList.as_view(), name='plate_list'),
    url(r'^plate/add/$', views.PlateCreate.as_view(), name='plate_add'),
    url(r'^plate/details/(?P<pk>[0-9]+)/$',
        views.PlateDetail.as_view(), name='plate_details'),
    url(r'^plate/edit/(?P<pk>[0-9]+)/$',
        views.PlateUpdate.as_view(), name='plate_edit'),
    url(r'^plate/(?P<pk>[0-9]+)/delete/$',
        views.PlateDelete.as_view(), name='plate_delete'),
    # Allergy
    url(r'^allergy/list/$', views.AllergyList.as_view(), name='allergy_list'),
    url(r'^allergy/add/$', views.AllergyCreate.as_view(), name='allergy_add'),
    url(r'^allergy/details/(?P<pk>[0-9]+)/$',
        views.AllergyDetail.as_view(), name='allergy_details'),
    url(r'^allergy/edit/(?P<pk>[0-9]+)/$',
        views.AllergyUpdate.as_view(), name='allergy_edit'),
    url(r'^allergy/(?P<pk>[0-9]+)/delete/$',
        views.AllergyDelete.as_view(), name='allergy_delete'),
]

mealcounter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# Import URLS
from core import urls as core_urls
from accounts import urls as accounts_urls
from meal import urls as meal_urls
from student import urls as student_urls


urlpatterns = [
    url(r'^', include(core_urls, namespace='core')),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^', include(meal_urls, namespace='meal')),
    url(r'^', include(student_urls, namespace='student')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # Student
    url(r'^student/list/$',
        views.StudentList.as_view(), name='student_list'),
    url(r'^student/add/$',
        views.StudentCreate.as_view(), name='student_add'),
    url(r'^student/details/(?P<pk>[0-9]+)/$',
        views.StudentDetail.as_view(), name='student_details'),
    url(r'^student/edit/(?P<pk>[0-9]+)/$',
        views.StudentUpdate.as_view(), name='student_edit'),
    url(r'^student/(?P<pk>[0-9]+)/delete/$',
        views.StudentDelete.as_view(), name='student_delete'),
    # Check
    url(r'^check/list/$',
        views.CheckList.as_view(), name='check_list'),
    url(r'^check/list/(?P<pk>[0-9]+)/$',
        views.check_list, name='check_admin_list'),
    url(r'^check/add/(?P<pk>[0-9]+)/$',
        views.check_in, name='check_add'),
    url(r'^check/details/(?P<pk>[0-9]+)/$',
        views.CheckDetail.as_view(), name='check_details'),
    url(r'^check/(?P<pk>[0-9]+)/delete/$',
        views.CheckDelete.as_view(), name='check_delete'),
]

student/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from meal.models import AuditModel, Plate, Meal, Allergy


class Student(User, AuditModel):
    GENDERS = (
        ('F', 'Feminino'),
        ('M', 'Masculino')
    )
    registration = models.CharField('Matrícula', max_length=255, default='')
    cpf = models.CharField('CPF', max_length=255, default='')
    rg = models.CharField('RG', max_length=255, default='')
    nickname = models.CharField(
        'Apelido', max_length=255, null=True, blank=True)
    gender = models.CharField(
        'Gênero', max_length=1, choices=GENDERS, default='')
    father_name = models.CharField('Nome do Pai', max_length=255, default='')
    father_occupation = models.CharField(
        'Profissão do Pai', max_length=255, default='')
    mother_name = models.CharField('Nome da Mãe', max_length=255, default='')
    mother_occupation = models.CharField(
        'Profissão da Mãe', max_length=255, default='')
    phone = models.CharField('Telefone', max_length=15, default='')
    birth = models.DateField('Data de Nascimento')
    postal_code = models.CharField('CEP', max_length=9, default='')
    city = models.CharField('Cidade', max_length=255, default='')
    address = models.CharField('Endereço', max_length=255, default='')
    address_number = models.CharField('Número', max_length=255, default='')
    district = models.CharField('Bairro', max_length=255, default='')
    reference = models.CharField(
        'Referência', max_length=255, null=True, blank=True)
    photo = models.ImageField(
        'Foto', upload_to='cadastro-aluno/', null=True, blank=True)
    allergy = models.ManyToManyField(
        Allergy,
        verbose_name='Alergias',
        related_name='allergy_student',
        blank=True)

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('student:student_list')

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'


class Check(AuditModel):
    student = models.ForeignKey(
        Student, verbose_name='Aluno', related_name='student_check')
    plate = models.ForeignKey(
        Plate, verbose_name='Prato', related_name='plate_check')
    meal = models.ForeignKey(
        Meal, verbose_name='Refeição', related_name='meal_check')

    def __str__(self):
        return '%s - %s' % (self.plate.name, self.student.get_full_name())

    def get_absolute_url(self):
        return reverse('student:check_list')

student/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from dal import autocomplete
from .models import Student, Check


class StudentForm(forms.ModelForm):
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Sobrenome')
    email = forms.EmailField(label='E-mail')

    class Meta:
        model = Student
        fields = [
            'registration', 'first_name', 'last_name', 'nickname', 'email',
            'cpf', 'rg', 'gender', 'father_name', 'father_occupation',
            'mother_name', 'mother_occupation', 'phone', 'birth',
            'postal_code', 'city', 'address', 'address_number', 'district',
            'reference', 'photo', 'allergy'
        ]
        widgets = {'allergy': autocomplete.ModelSelect2Multiple(
            url='meal:allergy_autocomplete')}

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data):
            raise forms.ValidationError("E-mail já registrado!")
        return data

class StudentUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Sobrenome')

    class Meta:
        model = Student
        fields = [
            'registration', 'first_name', 'last_name', 'nickname',
            'cpf', 'rg', 'gender', 'father_name', 'father_occupation',
            'mother_name', 'mother_occupation', 'phone', 'birth',
            'postal_code', 'city', 'address', 'address_number', 'district',
            'reference', 'photo', 'allergy'
        ]
        widgets = {'allergy': autocomplete.ModelSelect2Multiple(
            url='meal:allergy_autocomplete')}


class CheckForm(forms.ModelForm):

    class Meta:
        model = Check
        fields = '__all__'

student/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import Http404, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from meal.models import Meal, Plate, ItemMeal
from .models import Student, Check
from .forms import StudentForm, StudentUpdateForm, CheckForm


@method_decorator(login_required, name='dispatch')
class StudentList(ListView):

    paginate_by = 50
    model = Student
    template_name = 'student/list.html'


@method_decorator(login_required, name='dispatch')
class StudentCreate(CreateView):

    model = Student
    template_name = 'student/add.html'
    form_class = StudentForm


@method_decorator(login_required, name='dispatch')
class StudentUpdate(UpdateView):

    model = Student
    template_name = 'student/add.html'
    form_class = StudentUpdateForm


@method_decorator(login_required, name='dispatch')
class StudentDetail(DetailView):

    model = Student
    template_name = 'student/details.html'


@method_decorator(login_required, name='dispatch')
class StudentDelete(DeleteView):

    model = Student
    success_url = reverse_lazy('student:student_list')
    template_name = 'student/delete.html'


@method_decorator(login_required, name='dispatch')
class CheckList(ListView):

    paginate_by = 50
    model = Check
    template_name = 'check/list.html'


@login_required
def check_list(request, pk):
    try:
        student = Student.objects.get(pk=pk)
    except:
        raise Http404('Estudante não existe')

    dangerous_items = ItemMeal.objects.filter(
        allergy__in=student.allergy.values_list('pk'))
    dangerous_plates = []
    if dangerous_items:
        dangerous_plates = Plate.objects.filter(
            item_meal__in=dangerous_items.values_list('pk'))

    if request.method == 'GET':
        checks = Check.objects.filter(student=student)
        context = {
            'object_list': checks,
            'aluno': student,
            'dangerous_items': dangerous_items,
            'dangerous_plates': dangerous_plates
        }
        return render(
            request, 'check/admin/list.html', context)
    return HttpResponseNotFound("Página não encontrada")


@login_required
def check_in(request, pk):
    error = ''
    try:
        student = Student.objects.get(user_ptr=request.user)
        meal = Meal.objects.get(pk=pk)
    except:
        raise Http404('Refeição não existe')

    try:
        check = Check.objects.get(meal=meal, student=student)
    except:
        check = None

    if request.method == 'POST':
        if 'plate' in request.POST and request.POST['plate']:
            plate = Plate.objects.get(pk=request.POST['plate'])
            if check:
                check.plate = plate
            else:
                check = Check(student=student, meal=meal, plate=plate)
            check.save()
            return HttpResponseRedirect('/meal/student/list/')
        else:
            error = 'Por favor, selecione um prato.'
    context = {
        'meal': meal,
        'check': check,
        'error': error
    }
    return render(request, 'check/add.html', context)


@method_decorator(login_required, name='dispatch')
class CheckDetail(DetailView):

    model = Check
    template_name = 'check/details.html'


@method_decorator(login_required, name='dispatch')
class CheckDelete(DeleteView):

    model = Check
    success_url = reverse_lazy('student:check_list')
    template_name = 'check/delete.html'

student/templates/student/add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <nav class="navbar navbar-default">
        <div class="container">
            <a class="navbar-brand" href="#">Cadastro/Alteração dos Alunos</a>
            <ul class="nav navbar-nav pull-right">
                <li>
                    <p class="navbar-btn">
                        <a class="btn btn-default" href="{% url 'student:student_list' %}">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            Cancelar
                        </a>
                    </p>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <form action="." class="form-group" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <fieldset>
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="form-group has-error">
                                    <label class="control-label">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="text-danger">( * )</span>
                                        {% endif %}
                                    </label>
                                    {{ field|add_class:"form-control input-md" }}
                                    {% for error in field.errors%}
                                        <span class="help-block">{{ error}}</span>
                                        {% endfor%}
                                    </div>
                                {% else %}
                                    <div class="form-group">
                                        <label class="control-label">
                                            {{ field.label }}
                                            {% if field.field.required %}
                                                <span class="text-danger">( * )</span>
                                            {% endif %}
                                        </label>
                                        {{ field|add_class:"form-control input-md" }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div class="form-group">
                                <button type="submit" value="Salvar" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                                    Salvar
                                </button>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        {{ form.media }}
    {% endblock %}

student/templates/student/details.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <nav class="navbar navbar-default">
        <div class="container">
            <a class="navbar-brand" href="#">Dados do Aluno</a>
            <ul class="nav navbar-nav pull-right">
                <li>
                    <p class="navbar-btn">
                        <a class="btn btn-default nav-dist-btn" href="{% url  'student:student_list' %}">
                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                            Voltar
                        </a>
                    </p>
                </li>

                <li>
                    <p class="navbar-btn">
                        <a class="btn btn-default" href="{% url 'student:student_edit' object.id %}">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            Editar
                        </a>
                    </p>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <p>
                    <strong>Matrícula:</strong>
                    {{ object.registration }}
                </p>
                <p>
                    <strong>Nome Completo:</strong>
                    {{ object.get_full_name }}
                </p>
                <p>
                    <strong>CPF</strong>
                    {{ object.cpf }}
                </p>
                <p>
                    <strong>RG:</strong>
                    {{ object.rg }}
                </p>
                <p>
                    <strong>Apelido:</strong>
                    {{ object.nickname }}
                </p>
                <p>
                    <strong>Genêro:</strong>
                    {{ object.gender }}
                </p>
                <p>
                    <strong>Nome do Pai:</strong>
                    {{ object.father_name }}
                </p>
                <p>
                    <strong>Profissão do pai:</strong>
                    {{ object.father_occupation }}
                </p>
                <p>
                    <strong>Nome da Mãe:</strong>
                    {{ object.mother_occupation }}
                </p>
                <p>
                    <strong>Telefone:</strong>
                    {{ object.phone }}
                </p>
                <p>
                    <strong>Data de Nascimento:</strong>
                    {{ object.birth }}
                </p>
                <p>
                    <strong>CEP:</strong>
                    {{ object.postal_code }}
                </p>
                <p>
                    <strong>Cidade:</strong>
                    {{ object.city }}
                </p>
                <p>
                    <strong>Endereço:</strong>
                    {{ object.address }}
                </p>
                <p>
                    <strong>Número:</strong>
                    {{ object.address_number }}
                </p>
                <p>
                    <strong>Nome Completo:</strong>
                    {{ object.get_full_name }}
                </p>
                <p>
                    <strong>Bairro:</strong>
                    {{ object.district }}
                </p>
                <p>
                    <strong>Referência:</strong>
                    {{ object.reference }}
                </p>
                <p>
                    <strong>Foto:</strong>
                    {% if object.photo %}
                    <img class="photo-detail img-responsive img-rounded" src="{{ object.photo.url }}" alt="Foto" />
                    {% else %}
                    Não há foto registrada
                    {% endif %}
                </p>
                <hr>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Alergia(s)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for allergy in object.allergy.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'meal:allergy_details' allergy.pk %}">{{ allergy.name }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

student/templates/student/list.html
{% extends "base.html" %}

{% block body %}

    <nav class="navbar navbar-default">
        <div class="container">
            <a class="navbar-brand" href="#">Alunos</a>
            <ul class="nav navbar-nav pull-right">
                <li>
                    <p class="navbar-btn">
                        <a class="btn btn-default" href="{% url 'student:student_add' %}">
                            <i class="fa fa-file-o" aria-hidden="true"></i>
                            Novo
                        </a>
                    </p>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Check-In</th>
                            <th style="width: 21%;">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in object_list %}
                            <tr>
                                <td>{{ student.get_full_name }}</td>
                                <td>
                                    <a href="{% url 'student:check_admin_list' student.pk %}" class="btn btn-link">
                                        <i class="fa fa-list"></i> Visualizar
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'student:student_details' student.id %}" class="btn btn-default" title="Exibir">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </a>

                                    <a href="{% url 'student:student_edit' student.id %}" class="btn btn-default" title="Editar">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    </a>

                                    <a href="#modal-id-{{ student.id }}" class="btn btn-default" title="Remover" data-toggle="modal">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>

                            <!-- MODAL -->
                            <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
                                <div class="modal fade" id="modal-id-{{ student.id }}">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                <h4 class="modal-title">Alerta!</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Deseja realmente remover
                                                    <strong>{{ student.get_full_name }}</strong>?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <form action="{% url 'student:student_delete' student.pk %}" method="post">{%csrf_token%}
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                    <button type="submit" class="btn btn-danger" title="Deletar">
                                                        Excluir
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /MODAL -->
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}