accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import edit
from .forms import PasswordResetForm

urlpatterns = [
    # Edit User
    url(r'^user/edit/$', edit, name='edit'),
    # Login
    url(r'^login/$', views.login,
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', views.logout_then_login,
        {'login_url': 'core:index'}, name='logout'),
    # Recovery Password
    url(r'^password_change/$', views.password_change,
        {
            'template_name': 'accounts/password_change.html',
            'post_change_redirect': 'accounts:password_change_done'
        },
        name='password_change'),
    url(r'^password_change/done/$', views.password_change_done,
        {
            'template_name': 'accounts/password_change_done.html'
        },
        name='password_change_done'),
    url(r'^password_reset/$', views.password_reset,
        {
            'from_email': 'Nome <nrdesales@gmail.com>',
            'template_name': 'accounts/password_reset.html',
            'html_email_template_name': 'accounts/password_reset_email.html',
            # Template padrao sem formatação
            'email_template_name': 'accounts/password_reset_email.txt',
            'post_reset_redirect': 'accounts:password_reset_done',
            'password_reset_form': PasswordResetForm
        },
        name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        {
            'template_name': 'accounts/password_reset_done.html'
        },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm,
        {
            'template_name': 'accounts/password_reset_confirm.html',
            'post_reset_redirect': 'accounts:login'
        },
        name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete,
        {
            'template_name': 'accounts/password_reset_complete.html'
        },
        name='password_reset_complete'),
]

core/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    # Index
    url(r'^$', index, name='index'),
]

meal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Autocomplete
    url(r'^item-meal-autocomplete/$',
        views.ItemMealAutocomplete.as_view(), name='item_meal_autocomplete'),
    url(r'^plate-autocomplete/$',
        views.PlateAutocomplete.as_view(), name='plate_autocomplete'),
    url(r'^allergy-autocomplete/$',
        views.AllergyAutocomplete.as_view(), name='allergy_autocomplete'),
    # Meal
    url(r'^meal/list/$', views.MealList.as_view(), name='meal_list'),
    url(r'^meal/student/list/$',
        views.MealStudentList.as_view(), name='meal_student_list'),
    url(r'^meal/add/$', views.MealCreate.as_view(), name='meal_add'),
    url(r'^meal/details/(?P<pk>[0-9]+)/$',
        views.MealDetail.as_view(), name='meal_details'),
    url(r'^meal/edit/(?P<pk>[0-9]+)/$',
        views.MealUpdate.as_view(), name='meal_edit'),
    url(r'^meal/(?P<pk>[0-9]+)/delete/$',
        views.MealDelete.as_view(), name='meal_delete'),
    # ItemMeal
    url(r'^itemmeal/list/$',
        views.ItemMealList.as_view(), name='item_meal_list'),
    url(r'^itemmeal/add/$',
        views.ItemMealCreate.as_view(), name='item_meal_add'),
    url(r'^itemmeal/details/(?P<pk>[0-9]+)/$',
        views.ItemMealDetail.as_view(), name='item_meal_details'),
    url(r'^itemmeal/edit/(?P<pk>[0-9]+)/$',
        views.ItemMealUpdate.as_view(), name='item_meal_edit'),
    url(r'^itemmeal/(?P<pk>[0-9]+)/delete/$',
        views.ItemMealDelete.as_view(), name='item_meal_delete'),
    # Plate
    url(r'^plate/list/$', views.PlateList.as_view(), name='plate_list'),
    url(r'^plate/add/$', views.PlateCreate.as_view(), name='plate_add'),
    url(r'^plate/details/(?P<pk>[0-9]+)/$',
        views.PlateDetail.as_view(), name='plate_details'),
    url(r'^plate/edit/(?P<pk>[0-9]+)/$',
        views.PlateUpdate.as_view(), name='plate_edit'),
    url(r'^plate/(?P<pk>[0-9]+)/delete/$',
        views.PlateDelete.as_view(), name='plate_delete'),
    # Allergy
    url(r'^allergy/list/$', views.AllergyList.as_view(), name='allergy_list'),
    url(r'^allergy/add/$', views.AllergyCreate.as_view(), name='allergy_add'),
    url(r'^allergy/details/(?P<pk>[0-9]+)/$',
        views.AllergyDetail.as_view(), name='allergy_details'),
    url(r'^allergy/edit/(?P<pk>[0-9]+)/$',
        views.AllergyUpdate.as_view(), name='allergy_edit'),
    url(r'^allergy/(?P<pk>[0-9]+)/delete/$',
        views.AllergyDelete.as_view(), name='allergy_delete'),
]

mealcounter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# Import URLS
from core import urls as core_urls
from accounts import urls as accounts_urls
from meal import urls as meal_urls
from student import urls as student_urls


urlpatterns = [
    url(r'^', include(core_urls, namespace='core')),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^', include(meal_urls, namespace='meal')),
    url(r'^', include(student_urls, namespace='student')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # Student
    url(r'^student/list/$',
        views.StudentList.as_view(), name='student_list'),
    url(r'^student/add/$',
        views.StudentCreate.as_view(), name='student_add'),
    url(r'^student/details/(?P<pk>[0-9]+)/$',
        views.StudentDetail.as_view(), name='student_details'),
    url(r'^student/edit/(?P<pk>[0-9]+)/$',
        views.StudentUpdate.as_view(), name='student_edit'),
    url(r'^student/(?P<pk>[0-9]+)/delete/$',
        views.StudentDelete.as_view(), name='student_delete'),
    # Check
    url(r'^check/list/$',
        views.CheckList.as_view(), name='check_list'),
    url(r'^check/list/(?P<pk>[0-9]+)/$',
        views.check_list, name='check_admin_list'),
    url(r'^check/add/(?P<pk>[0-9]+)/$',
        views.check_in, name='check_add'),
    url(r'^check/details/(?P<pk>[0-9]+)/$',
        views.CheckDetail.as_view(), name='check_details'),
    url(r'^check/(?P<pk>[0-9]+)/delete/$',
        views.CheckDelete.as_view(), name='check_delete'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect
from student.models import Student

# Página inicial


def index(request):
    if (request.user.is_authenticated() and
            Student.objects.filter(user_ptr=request.user).exists()):
        return HttpResponseRedirect('/meal/student/list/')

    return render(request, 'index.html')

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
	<link rel="icon" href="{% static 'images/a.ico'%}"/>
	<script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>

	<title>SEA</title>
</head>
<body>
	<!-- NAVBAR -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- agrupar para mobile -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<!-- links da navbar -->
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<!-- ícone na navbar -->
				<ul class="nav navbar-nav">
					<li>
						<p class="navbar-btn">
							<a href="{% url 'core:index' %}">
								<img src="{% static 'images/icon-md.png' %}" class='img-responsive' title="Easy Oral Health">
							</a>
						</p>
					</li>
				</ul>
				{% if student %}
					{% include "navbar_student.html" %}
				{% elif user.is_authenticated and user.is_superuser %}
					{% include "navbar_admin.html" %}
				{% else %}
					{% include "navbar_default.html" %}
				{% endif %}
			</div><!-- /.navbar-collapse -->
		</div>
	</nav>
	<!-- NAVBAR -->

	<!-- Mensagens -->
	<div class="container">
    	<div class="row">
        	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				{% if messages %}
			        {% for message in messages %}
			        <div class="alert alert-info">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Atenção</strong>
			        	<p>{{ message }}</p>
					</div>
			        {% endfor %}
				{% endif %}
			</div>
		</div>
	</div>

	{% block body %}
	{% endblock %}

	{% block scripts %}
	{% endblock %}
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div style="margin-top: 3em;">
        <center>
          <img src="{% static 'images/logo.png' %}" class='img-responsive'> 
          <center></center><h1>Bem-vindo ao SEA</h1></center>
          <center><p>Sistema de Auxílio Alimentar ao Estudante.</p></center>
          <h1><b>{{ get_user_logged }}</b></h1>
        </center>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/navbar_admin.html
<ul class="nav navbar-nav">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-cutlery" aria-hidden="true"></i>
            Refeições
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="{% url 'meal:plate_list' %}">
              <i class="fa fa-table" aria-hidden="true"></i>
              Pratos Feitos
            </a>
          </li>
            <li>
                <a href="{% url 'meal:item_meal_list' %}">
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    Itens da Refeição
                </a>
            </li>
            <li>
                <a href="{% url 'meal:allergy_list' %}">
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    Alergias
                </a>
            </li>
        </ul>
    </li>
    <li>
        <a href="{% url 'meal:meal_list' %}">
            <i class="fa fa-calendar" aria-hidden="true"></i>
            Horários
        </a>
    </li>
</ul>
<ul class="nav navbar-nav">
    <li class="dropdown">
        <a href="{% url 'student:student_list' %}">
            <i class="glyphicon glyphicon-user" aria-hidden="true"></i>
            Alunos
        </a>
    </li>
    <li>
        <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                    {{ user.first_name }}
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'accounts:edit' %}" title="Editar os dados do usuário">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            Editar
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:password_change' %}">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            Altera senha
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            Sair
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

core/templates/navbar_default.html
<ul class="nav navbar-nav">
    <li>
        <a href="{% url 'core:index' %}">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
            Início
        </a>
    </li>
</ul>

<ul class="nav navbar-nav navbar-right">
    <li>
        <a href="{% url 'accounts:login' %}">
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
            Entrar
        </a>
    </li>
</ul>

core/templates/navbar_student.html
<ul class="nav navbar-nav">
    <li>
        <a href="{% url 'meal:meal_student_list' %}">
            <i class="glyphicon glyphicon-cutlery" aria-hidden="true"></i>
            Refeições
        </a>
    </li>
    <li>
        <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                    {{ user.first_name }}
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'accounts:edit' %}" title="Editar os dados do usuário">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            Editar
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:password_change' %}">
                            <i class="fa fa-key" aria-hidden="true"></i>
                            Altera senha
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            Sair
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>