core/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    # Index
    url(r'^$', index, name='index'),
]

meal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Autocomplete
    url(r'^item-meal-autocomplete/$',
        views.ItemMealAutocomplete.as_view(), name='item_meal_autocomplete'),
    url(r'^plate-autocomplete/$',
        views.PlateAutocomplete.as_view(), name='plate_autocomplete'),
    url(r'^allergy-autocomplete/$',
        views.AllergyAutocomplete.as_view(), name='allergy_autocomplete'),
    # Meal
    url(r'^meal/list/$', views.MealList.as_view(), name='meal_list'),
    url(r'^meal/student/list/$',
        views.MealStudentList.as_view(), name='meal_student_list'),
    url(r'^meal/add/$', views.MealCreate.as_view(), name='meal_add'),
    url(r'^meal/details/(?P<pk>[0-9]+)/$',
        views.MealDetail.as_view(), name='meal_details'),
    url(r'^meal/edit/(?P<pk>[0-9]+)/$',
        views.MealUpdate.as_view(), name='meal_edit'),
    url(r'^meal/(?P<pk>[0-9]+)/delete/$',
        views.MealDelete.as_view(), name='meal_delete'),
    # ItemMeal
    url(r'^itemmeal/list/$',
        views.ItemMealList.as_view(), name='item_meal_list'),
    url(r'^itemmeal/add/$',
        views.ItemMealCreate.as_view(), name='item_meal_add'),
    url(r'^itemmeal/details/(?P<pk>[0-9]+)/$',
        views.ItemMealDetail.as_view(), name='item_meal_details'),
    url(r'^itemmeal/edit/(?P<pk>[0-9]+)/$',
        views.ItemMealUpdate.as_view(), name='item_meal_edit'),
    url(r'^itemmeal/(?P<pk>[0-9]+)/delete/$',
        views.ItemMealDelete.as_view(), name='item_meal_delete'),
    # Plate
    url(r'^plate/list/$', views.PlateList.as_view(), name='plate_list'),
    url(r'^plate/add/$', views.PlateCreate.as_view(), name='plate_add'),
    url(r'^plate/details/(?P<pk>[0-9]+)/$',
        views.PlateDetail.as_view(), name='plate_details'),
    url(r'^plate/edit/(?P<pk>[0-9]+)/$',
        views.PlateUpdate.as_view(), name='plate_edit'),
    url(r'^plate/(?P<pk>[0-9]+)/delete/$',
        views.PlateDelete.as_view(), name='plate_delete'),
    # Allergy
    url(r'^allergy/list/$', views.AllergyList.as_view(), name='allergy_list'),
    url(r'^allergy/add/$', views.AllergyCreate.as_view(), name='allergy_add'),
    url(r'^allergy/details/(?P<pk>[0-9]+)/$',
        views.AllergyDetail.as_view(), name='allergy_details'),
    url(r'^allergy/edit/(?P<pk>[0-9]+)/$',
        views.AllergyUpdate.as_view(), name='allergy_edit'),
    url(r'^allergy/(?P<pk>[0-9]+)/delete/$',
        views.AllergyDelete.as_view(), name='allergy_delete'),
]

mealcounter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# Import URLS
from core import urls as core_urls
from accounts import urls as accounts_urls
from meal import urls as meal_urls
from student import urls as student_urls


urlpatterns = [
    url(r'^', include(core_urls, namespace='core')),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^', include(meal_urls, namespace='meal')),
    url(r'^', include(student_urls, namespace='student')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meal/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class AuditModel(models.Model):
    created_on = models.DateTimeField('Criado em', auto_now_add=True)
    updated_on = models.DateTimeField('Autalizado em', auto_now=True)

    class Meta:
        abstract = True


class Allergy(AuditModel):
    name = models.CharField('Descrição', max_length=100, default='')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('meal:allergy_list')

    class Meta:
        verbose_name = 'Alergia'
        verbose_name_plural = 'Alergias'


class ItemMeal(AuditModel):
    name = models.CharField('Nome', max_length=100, default='')
    properties = models.TextField(
        'Propriedades', max_length=100, null=True, blank=True)
    allergy = models.ManyToManyField(
        Allergy,
        verbose_name='Alergias',
        related_name='allergy_item',
        blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('meal:item_meal_list')

    class Meta:
        verbose_name = 'Item Refeição'
        verbose_name_plural = 'Itens da Refeição'
        ordering = ['-id']


class Plate(AuditModel):
    name = models.CharField('Descrição', max_length=100)
    item_meal = models.ManyToManyField(
        ItemMeal, verbose_name='Itens da Refeição', related_name='item_plate')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('meal:plate_list')

    class Meta:
        verbose_name = 'Prato Feito'
        verbose_name_plural = 'Pratos Feitos'
        ordering = ['-id']


class Meal(AuditModel):
    date = models.DateField('Data')
    estimate = models.IntegerField('Estimativa')
    start_time = models.TimeField('Início')
    end_time = models.TimeField('Término')
    status = models.BooleanField('Ativo')
    plate = models.ManyToManyField(
        Plate, verbose_name='Prato', related_name='plate_meal')

    def __str__(self):
        return str(self.date)

    def get_absolute_url(self):
        return reverse('meal:meal_list')

    class Meta:
        verbose_name = 'Refeição'
        verbose_name_plural = 'Refeições'
        ordering = ['-id']

meal/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Meal, ItemMeal, Plate, Allergy
from dal import autocomplete


class MealForm(forms.ModelForm):

    class Meta:
        model = Meal
        fields = '__all__'
        widgets = {'plate': autocomplete.ModelSelect2Multiple(
            url='meal:plate_autocomplete')}


class ItemMealForm(forms.ModelForm):

    class Meta:
        model = ItemMeal
        fields = '__all__'
        widgets = {'allergy': autocomplete.ModelSelect2Multiple(
            url='meal:allergy_autocomplete')}


class PlateForm(forms.ModelForm):

    class Meta:
        model = Plate
        fields = '__all__'
        widgets = {'item_meal': autocomplete.ModelSelect2Multiple(
            url='meal:item_meal_autocomplete')}


class AllergyForm(forms.ModelForm):

    class Meta:
        model = Allergy
        fields = '__all__'

meal/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone
from dal import autocomplete
from .models import Meal, ItemMeal, Plate, Allergy
from .forms import MealForm, ItemMealForm, PlateForm, AllergyForm


@method_decorator(login_required, name='dispatch')
class MealList(ListView):
    paginate_by = 50
    model = Meal
    template_name = 'meal/list.html'


@method_decorator(login_required, name='dispatch')
class MealStudentList(ListView):
    paginate_by = 50
    model = Meal
    template_name = 'meal/student/list.html'

    def get_context_data(self, **kwargs):
        context = super(MealStudentList, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


@method_decorator(login_required, name='dispatch')
class MealCreate(CreateView):
    model = Meal
    template_name = 'meal/add.html'
    form_class = MealForm


@method_decorator(login_required, name='dispatch')
class MealUpdate(UpdateView):
    model = Meal
    template_name = 'meal/add.html'
    form_class = MealForm


@method_decorator(login_required, name='dispatch')
class MealDetail(DetailView):
    model = Meal
    template_name = 'meal/details.html'


@method_decorator(login_required, name='dispatch')
class MealDelete(DeleteView):
    model = Meal
    success_url = reverse_lazy('meal:meal_list')
    template_name = 'meal/delete.html'


# Autocomplete itemmeal

class ItemMealAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        qs = ItemMeal.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


@method_decorator(login_required, name='dispatch')
class ItemMealList(ListView):
    model = ItemMeal
    template_name = 'itemmeal/list.html'


@method_decorator(login_required, name='dispatch')
class ItemMealCreate(CreateView):
    model = ItemMeal
    template_name = 'itemmeal/add.html'
    form_class = ItemMealForm


@method_decorator(login_required, name='dispatch')
class ItemMealUpdate(UpdateView):
    model = ItemMeal
    template_name = 'itemmeal/add.html'
    form_class = ItemMealForm


@method_decorator(login_required, name='dispatch')
class ItemMealDetail(DetailView):
    model = ItemMeal
    template_name = 'itemmeal/details.html'


@method_decorator(login_required, name='dispatch')
class ItemMealDelete(DeleteView):
    model = ItemMeal
    success_url = reverse_lazy('meal:item_meal_list')
    template_name = 'itemmeal/delete.html'


# Autocomplete itemmeal

class PlateAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        qs = Plate.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


@method_decorator(login_required, name='dispatch')
class PlateList(ListView):
    paginate_by = 60
    model = Plate
    template_name = 'plate/list.html'


@method_decorator(login_required, name='dispatch')
class PlateCreate(CreateView):
    model = Plate
    template_name = 'plate/add.html'
    form_class = PlateForm


@method_decorator(login_required, name='dispatch')
class PlateUpdate(UpdateView):
    model = Plate
    template_name = 'plate/add.html'
    form_class = PlateForm


@method_decorator(login_required, name='dispatch')
class PlateDetail(DetailView):
    model = Plate
    template_name = 'plate/details.html'


@method_decorator(login_required, name='dispatch')
class PlateDelete(DeleteView):
    model = Plate
    success_url = reverse_lazy('meal:plate_list')
    template_name = 'plate/delete.html'


# Autocomplete itemmeal

class AllergyAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        qs = Allergy.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


@method_decorator(login_required, name='dispatch')
class AllergyList(ListView):
    model = Allergy
    template_name = 'allergy/list.html'


@method_decorator(login_required, name='dispatch')
class AllergyCreate(CreateView):
    model = Allergy
    template_name = 'itemmeal/add.html'
    form_class = AllergyForm


@method_decorator(login_required, name='dispatch')
class AllergyUpdate(UpdateView):
    model = Allergy
    template_name = 'allergy/add.html'
    form_class = AllergyForm


@method_decorator(login_required, name='dispatch')
class AllergyDetail(DetailView):
    model = Allergy
    template_name = 'allergy/details.html'


@method_decorator(login_required, name='dispatch')
class AllergyDelete(DeleteView):
    model = Allergy
    success_url = reverse_lazy('meal:allergy_list')
    template_name = 'allergy/delete.html'

meal/templates/itemmeal/add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
<nav class="navbar navbar-default">
	<div class="container">
		<a class="navbar-brand" href="#">Cadastro/Alteração dos Itens da Refeição</a>
		<ul class="nav navbar-nav pull-right">
			<li>
				<p class="navbar-btn">
					<a class="btn btn-default" href="{% url 'meal:item_meal_list' %}"> 
						<i class="fa fa-times" aria-hidden="true"></i>
						Cancelar
					</a>
				</p>
			</li>
		</ul>
	</div>
</nav>

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<form action="." class="form-group" method="post">{% csrf_token %}
				<fieldset>
					{% for field in form %}
					{% if field.errors %}
					<div class="form-group error" >
						<label class="control-label" >{{ field.label }}</label>
						{{ field|add_class:"form-control input-md" }}
						{% for error in field.errors%}
						<span class="help-inline error">{{ error}}</span>
						{% endfor%}
					</div>
					{%else%}
					<div class="form-group">
						<label class="control-label" >{{ field.label }}</label>
						{{ field|add_class:"form-control input-md" }}
					</div>
					{%endif%}
					{% endfor %}
					<div class="form-group">
						<button type="submit" value="Salvar" class="btn btn-primary">
							<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
							Salvar
						</button>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
</div>
{{ form.media }}
{% endblock %}

meal/templates/itemmeal/details.html
{% extends 'base.html' %}

{% block body %}

    <nav class="navbar navbar-default">
        <div class="container">
            <a class="navbar-brand" href="#">Dados do Item da Refeição</a>
            <ul class="nav navbar-nav pull-right">
                <li>
                    <p class="navbar-btn">
                        <a class="btn btn-default nav-dist-btn" href="{% url 'meal:item_meal_list' %}">
                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                            Voltar
                        </a>
                    </p>
                </li>

                <li>
                    <p class="navbar-btn">
                        <a class="btn btn-default" href="{% url 'meal:item_meal_edit' object.id %}">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            Editar
                        </a>
                    </p>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <p>
                    <strong>Nome:</strong>
                    {{ object.name }}
                </p>
                <p>
                    <strong>Propriedades:</strong>
                    {{ object.properties }}
                </p>
            </div>
        </div>
        <hr/>
        <div class="col-md-6">
            <h5>Alergia(s)</h5>
            <hr/>
            {% if not object.allergy.exists %}
                Não é alérgico
            {% else %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                </thead>
                <tbody>
                    {% for allergy in object.allergy.all %}
                    <tr>
                        <td>
                            <a href="{% url 'meal:allergy_details' allergy.pk %}">{{ allergy.name }}</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <div class="col-md-6">
            <h5>Prato(s)</h5>
            <hr/>
            {% if not object.item_plate.exists %}
                Não está em nenhum prato
            {% else %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                </thead>
                <tbody>
                    {% for plate in object.item_plate.all %}
                    <tr>
                        <td>
                            <a href="{% url 'meal:plate_details' plate.pk %}">{{ plate.name }}</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>

{% endblock %}

meal/templates/itemmeal/list.html
{% extends 'base.html' %}

{% block body %}

<nav class="navbar navbar-default">
	<div class="container">
		<a class="navbar-brand" href="#">Itens da Refeição</a>
		<ul class="nav navbar-nav pull-right">
			<li>
				<p class="navbar-btn">
					<a class="btn btn-default" href="{% url 'meal:item_meal_add' %}"> 
						<i class="fa fa-file-o" aria-hidden="true"></i>
						Novo
					</a>
				</p>
			</li>
		</ul>
	</div>
</nav>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Quantidade</th>
						<th>Valor</th>
						<th>Propiedades</th>
						<th style="width: 21%;">Ações</th>
					</tr>
				</thead>
				<tbody>
					{% for itemmeal in object_list %}
					<tr>
						<td>{{ itemmeal.name }}</td>
						<td>{{ itemmeal.amount }}</td>
						<td>{{ itemmeal.value }}</td>
						<td>{{ itemmeal.properties }}</td>
						<td>                    
							<a href="{% url 'meal:item_meal_details' itemmeal.id %}" class="btn btn-default" title="Exibir">
								<i class="fa fa-search" aria-hidden="true"></i>
							</a>

							<a href="{% url 'meal:item_meal_edit' itemmeal.id %}" class="btn btn-default" title="Editar">
								<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
							</a>

							<a href="#modal-id-{{ itemmeal.id }}" class="btn btn-default" title="Remover" data-toggle="modal">
								<i class="fa fa-trash-o" aria-hidden="true"></i>
							</a>
						</td>
					</tr>

					<!-- MODAL -->
					<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
						<div class="modal fade" id="modal-id-{{ itemmeal.id }}">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
										<h4 class="modal-title">Alerta!</h4>
									</div>
									<div class="modal-body">
										<p>Deseja realmente remover <strong>{{ itemmeal.name }}</strong>?</p>
									</div>
									<div class="modal-footer">
										<form action="{% url 'meal:item_meal_delete' itemmeal.pk %}" method="post">{%csrf_token%}
											<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
											<button type="submit" class='btn btn-danger' title='Deletar'>
												Excluir
											</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /MODAL -->
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}